---
version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    env_file: .env
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./data/influxdb2:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "$UID:$GID"
    env_file: .env
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_INSTALL_PLUGINS:
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - 3001:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped
